set nocompatible
runtime! config/**/*.vim
call pathogen#infect()
call pathogen#helptags()
set mouse=a
set relativenumber
filetype plugin indent on
filetype plugin on
syntax enable
set tabstop=2
set softtabstop=2
set expandtab
let g:NERDSpaceDelims = 1
set background=dark
set shiftwidth=4
python from powerline.vim import setup as powerline_setup
python powerline_setup()
python del powerline_setup
set rtp+=~/Library/Python/2.7/lib/python/site-packages/powerline/bindings/vim
