set nocompatible
runtime! config/**/*.vim
call pathogen#infect()
call pathogen#helptags()
set mouse=a
set relativenumber
filetype plugin indent on
filetype plugin on
syntax enable
set tabstop=2
set softtabstop=2
set expandtab
let g:NERDSpaceDelims = 1
set background=dark
set shiftwidth=4
